# Generated by Django 2.2.2 on 2019-07-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rectangle',
            name='rec_height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rectangle',
            name='rec_width',
            field=models.IntegerField(),
        ),
    ]
