# Generated by Django 2.2.2 on 2019-07-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_app', '0003_rectangle_date_recorded'),
    ]

    operations = [
        migrations.CreateModel(
            name='FanUnbalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impeller_mass', models.IntegerField()),
                ('fan_speed', models.IntegerField()),
                ('backplate_dia', models.IntegerField()),
            ],
        ),
    ]
